//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DothanTech.BaoJia.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommandTable
    {
        public RecommandTable()
        {
            this.Brand = new HashSet<Brand>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Brand> Brand { get; set; }
    }
}
