//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryArea
    {
        public int Id { get; set; }
        public string TargetAddress { get; set; }
        public Nullable<float> Value1 { get; set; }
        public Nullable<float> Value2 { get; set; }
        public Nullable<float> Value3 { get; set; }
    }
}
